services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: northwind-sqlserver
    user: "root"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "J0su3.V2024E$"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - ./data/sqlserver:/var/opt/mssql
    restart: unless-stopped