services:
  sqlserver:
    platform: linux/amd64
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: northwind-sqlserver
    user: "root"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "J0su3.V2024E$"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  api:
    build:
      context: ./project_API
      dockerfile: Northwind.WebAPI/Dockerfile
    container_name: northwind-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=NorthwindDB;User Id=sa;Password=J0su3.V2024E$;TrustServerCertificate=True;MultipleActiveResultSets=True
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: northwind-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - api
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  sqlserver_data: